language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
    cd ./example;
    pip install virtualenv;
    npm install -g bower grunt grunt-cli;
    gem install sass;
    make install;

# command to run tests
script:
   make test

addons:
  apt:
    packages:
    - nodejs
    - npm
    - ruby-full
    - rubygems
    - xvfb
    - sqlite
    - sloccount
    - libjpeg-dev
    - libpng-dev
    - gettext
